### ISSUE TITLE
from_scvi_model

### ISSUE THREAD

**Issue by cdiaz45** [theislab/scib-pipeline#41]
Hello, 
Thank you for the documentation and all the work you have done on integration. 

I find that an error occurs when running scvi. The error is right at the end of the process and it appears to do with "TypeError: from_scvi_model() missing 1 required positional argument: 'unlabeled_category'"
When I comment out the scvi from the config, the whole pipeline seems to work fine.  
Have you encountered this error before? 

Thank you in advance, Carmen

Traceback (most recent call last):
  File "scripts/integration/runIntegration.py", line 81, in <module>
    runIntegration(file, out, run, hvg, batch, celltype)
  File "scripts/integration/runIntegration.py", line 34, in runIntegration
    integrated = method(adata, batch, celltype)
  File "/home/ubuntu/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/integration.py", line 281, in scanvi
    unknown_category="UnknownUnknown",  # pick anything definitely not in a dataset
TypeError: from_scvi_model() missing 1 required positional argument: 'unlabeled_category'

 `conda run python scripts/integration/runIntegration.py -i integration_test/test_data_r4/prepare/unscaled/full_feature/adata_pre.h5ad -o integration_test/test_data_r4/integration/unscaled/full_feature/scanvi.h5ad -b batch --method scanvi -c celltype` failed. (See above for error)`

**Comment by LuckyMD** [comment]
Hi!

We recently updated the scvi code in the repo (last week), so this must be a bug we missed. It sounds like just a parameter naming mismatch. Which version of scvi-tools do you have in your environment?

**Comment by cdiaz45** [comment]
Hello, the version I have seems to be the latest. scvi-tools in /home/ubuntu/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages (0.16.4). However, I wonder if the python version is the issue. When I start python and try to import the scvi, it gives me an error to do GLIBCXX_3.4.30. I have tried many ways to update to GLIBCXX_3.4.30, but haven't been able to. But then, equally, not sure why it runs when I start the snakemake pipeline and only dies at the end.

**Comment by cdiaz45** [comment]
Also maybe related or unrelated. If I set up a new environment for scvi as in the docs: conda create -n scvi-env python=3.9, but I install with conda forge, I get import problems. I can avoid those problems by using pip install scvi-tools. So I will try to install scvi with pip in the scib-pipeline-R4.0 just to check. The error when I use conda forge: (ImportError: /home/ubuntu/miniconda3/envs/scvi-env/lib/python3.9/site-packages/h5py/defs.cpython-39-x86_64-linux-gnu.so: undefined symbol: H5Pset_fapl_ros3).

**Comment by littleju714** [comment]
> Also maybe related or unrelated. If I set up a new environment for scvi as in the docs: conda create -n scvi-env python=3.9, but I install with conda forge, I get import problems. I can avoid those problems by using pip install scvi-tools (someone posted somewhat similar issues with h5py). So I will try to install scvi with pip in the scib-pipeline-R4.0 just to check. The error when I use conda forge: (ImportError: /home/ubuntu/miniconda3/envs/scvi-env/lib/python3.9/site-packages/h5py/defs.cpython-39-x86_64-linux-gnu.so: undefined symbol: H5Pset_fapl_ros3).

Hi, I also got the same error. I tried to revise this file: 

> miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/integration.py", line 281, in scanvi
>     unknown_category="UnknownUnknown",  # pick anything definitely not in a dataset

"unknown_category" to "unlabeled_category". 

And it seem to work. It goes like this:

> snakemake --configfile configs/test_data-R4.0.yaml --cores 24
> Building DAG of jobs...
> Nothing to be done (all requested files are present and up to date).
> Complete log: .snakemake/log/2022-06-29T155249.803624.snakemake.log

Do you fix it by install scvi-tools by pip?

**Comment by LuckyMD** [comment]
This is a great discussion thread! @littleju714 would you be up for creating a small PR with the fix?

@mumichae we might need to change the scvi install in the env files if the pip install works better. Maybe the version in conda-forge is not maintained? Would be good to check with @agayoso.

**Comment by cdiaz45** [comment]
Hello, I tried with pip, but it takes me in a rabbit hall of conflicts with other packages and with tensorflow so I couldn't get it working in the end. Maybe if I change the "unknown_category" to "unlabeled_category"? Will try that. Thank you again.

**Comment by littleju714** [comment]
I think I revise the scib package, not the scib-pipeline. 

And as for the GLIBCXX_3.4.30 error, I fixed it by doing this:
`conda install libgcc`
And if it doesn't work for you, you can try to find the location of lib and put it in the path:
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/user/miniconda3/lib/`

And then another error occured:  libffi.so.7: cannot open shared object file: No such file or directory
It's because it finds the libffi.so.7.1.0, you can copy or link the correct one.
`cp miniconda3/lib/libffi.so.7 miniconda3/envs/scib-pipeline-R4.0/lib/`

**Comment by cdiaz45** [comment]
Thank you, will try that and also isolating in a separate env as it has been suggested.

**Comment by adamgayoso** [comment]
Related: https://github.com/theislab/scib/issues/324

**Comment by mumichae** [comment]
There have been some updates in dependencies recently. I will close this thread for now. Please open up a new issues for any problems that still persist
